[project]
name = "ADM"
version = "0.1.0"
description = "An Web-Site to administrate your life"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asgiref==3.8.1",
    "django==5.2.3",
    "django-colorfield>=0.14.0",
    "django-mathfilters>=1.0.0",
    "sqlparse==0.5.3",
]
