# Generated by Django 5.2.3 on 2025-08-09 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da configuração do agente', max_length=200)),
                ('model', models.CharField(default='gpt-3.5-turbo', help_text='Modelo de IA a ser usado', max_length=100)),
                ('temperature', models.FloatField(default=0.7, help_text='Criatividade do modelo (0.0 - 1.0)')),
                ('max_tokens', models.IntegerField(default=1000, help_text='Máximo de tokens na resposta')),
                ('system_prompt', models.TextField(help_text='Prompt do sistema que define o comportamento do agente')),
                ('description', models.TextField(blank=True, help_text='Descrição da configuração', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Agente',
                'verbose_name_plural': 'Configurações dos Agentes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da conversa', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentAi.agentconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=10)),
                ('content', models.TextField(help_text='Conteúdo da mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(default=0, help_text='Tokens utilizados nesta mensagem')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agentAi.conversation')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do template', max_length=200)),
                ('category', models.CharField(help_text='Categoria do prompt', max_length=100)),
                ('template', models.TextField(help_text='Template do prompt com variáveis {{variavel}}')),
                ('description', models.TextField(blank=True, help_text='Descrição do template', null=True)),
                ('variables', models.JSONField(default=list, help_text='Lista de variáveis necessárias')),
                ('is_public', models.BooleanField(default=False, help_text='Visível para outros usuários')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Prompt',
                'verbose_name_plural': 'Templates de Prompts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
