# Generated by Django 5.2.3 on 2025-08-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentAi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='agent_config',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='user',
        ),
        migrations.DeleteModel(
            name='AgentConfig',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='PromptTemplate',
        ),
    ]
