# Generated by Django 5.2.3 on 2025-08-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='description',
            field=models.CharField(default='gell', max_length=300),
            preserve_default=False,
        ),
    ]
