# Generated by Django 5.2.3 on 2025-08-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0002_expensecategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='spent_at',
            field=models.DateField(),
        ),
    ]
