# Generated by Django 5.2.3 on 2025-08-08 02:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0003_alter_expenses_spent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
