# Generated by Django 5.2.3 on 2025-08-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_manager', '0005_incomecategorys_incomes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomes',
            old_name='spent_at',
            new_name='received_at',
        ),
        migrations.AlterField(
            model_name='incomes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_manager.incomecategorys'),
        ),
    ]
