# Generated by Django 5.2.3 on 2025-08-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_bio_remove_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_ai',
            field=models.BooleanField(default=False),
        ),
    ]
