# Generated by Django 5.2.3 on 2025-08-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_has_ai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_ai',
            new_name='is_premium',
        ),
    ]
