name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: [ self-hosted, ec2, prod ]   # matches your runner labels
    env:
      APP_DIR: /home/ec2-user/Adm
      VENV: /home/ec2-user/Adm/.venv
      PYVER: "3.13"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv if missing
        shell: bash
        run: |
          if ! command -v uv >/dev/null 2>&1; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
          fi
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.bashrc"
          export PATH="$HOME/.local/bin:$PATH"
          uv --version

      - name: Sanitize Python env
        shell: bash
        run: |
          unset PYTHONHOME PYTHONPATH || true
          export -n PYTHONHOME PYTHONPATH || true

      - name: Rsync repo to app dir
        shell: bash
        run: |
          rsync -a --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '.env' \
            --exclude 'media/' \
            "$GITHUB_WORKSPACE"/ "$APP_DIR"/

      - name: Ensure venv with uv
        shell: bash
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          uv python install "$PYVER"
          uv venv --python "$PYVER" "$VENV"

      - name: Install deps with uv
        shell: bash
        working-directory: ${{ env.APP_DIR }}
        run: |
          if [ -f "pyproject.toml" ]; then
            uv sync --no-dev --python "$VENV/bin/python"
          elif [ -f "requirements.txt" ]; then
            uv pip install --python "$VENV/bin/python" -r requirements.txt
          fi

      - name: Django migrate
        shell: bash
        working-directory: ${{ env.APP_DIR }}
        run: "$VENV/bin/python" manage.py migrate --noinput

      - name: Collect static
        shell: bash
        working-directory: ${{ env.APP_DIR }}
        run: "$VENV/bin/python" manage.py collectstatic --noinput

      - name: Restart services
        shell: bash
        run: |
          sudo systemctl restart gunicorn
          sudo systemctl reload nginx
